/**
 * YouTube transcript fetcher — extracted from @kimtaeyoon83/mcp-server-youtube-transcript
 * Uses YouTube's internal get_transcript API with ANDROID client for reliability.
 * @see https://github.com/kimtaeyoon83/mcp-server-youtube-transcript
 */

import https from "node:https";

export interface TranscriptLine {
  text: string;
  start: number;
  dur: number;
}

export interface TranscriptSegment {
  text: string;
  start: number;
  end: number;
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface VideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  publishDate: string;
}

export interface SubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  metadata: VideoMetadata;
}

const REQUEST_TIMEOUT = 30_000;
const ANDROID_CLIENT_VERSION = "19.29.37";
const ANDROID_USER_AGENT = `com.google.android.youtube/${ANDROID_CLIENT_VERSION} (Linux; U; Android 11) gzip`;
const WEB_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const DEFAULT_CLIENT_VERSION = "2.20251201.01.00";

function encodeVarint(value: number): number[] {
  const bytes: number[] = [];
  while (value > 0x7f) {
    bytes.push((value & 0x7f) | 0x80);
    value >>>= 7;
  }
  bytes.push(value);
  return bytes;
}

function buildParams(videoId: string, lang: string = "en"): string {
  const innerParts: number[] = [
    0x0a,
    0x03,
    ...Buffer.from("asr"),
    0x12,
    ...encodeVarint(lang.length),
    ...Buffer.from(lang),
    0x1a,
    0x00,
  ];
  const innerBuf = Buffer.from(innerParts);
  const innerB64 = innerBuf.toString("base64");
  const innerEncoded = encodeURIComponent(innerB64);

  const panelName = "engagement-panel-searchable-transcript-search-panel";
  const outerParts: number[] = [
    0x0a,
    ...encodeVarint(videoId.length),
    ...Buffer.from(videoId),
    0x12,
    ...encodeVarint(innerEncoded.length),
    ...Buffer.from(innerEncoded),
    0x18, 0x01,
    0x2a,
    ...encodeVarint(panelName.length),
    ...Buffer.from(panelName),
    0x30, 0x01,
    0x38, 0x01,
    0x40, 0x01,
  ];

  return Buffer.from(outerParts).toString("base64");
}

function httpsRequest(
  options: https.RequestOptions,
  data?: string
): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.request(
      { ...options, timeout: REQUEST_TIMEOUT },
      (res) => {
        if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
          reject(new Error(`HTTP ${res.statusCode}: ${res.statusMessage || "Unknown error"}`));
          return;
        }
        let body = "";
        res.on("data", (chunk) => (body += chunk));
        res.on("end", () => resolve(body));
      }
    );

    req.on("error", (err) => reject(new Error(`Network error: ${err.message}`)));
    req.on("timeout", () => {
      req.destroy();
      reject(new Error(`Request timeout after ${REQUEST_TIMEOUT}ms`));
    });

    if (data) req.write(data);
    req.end();
  });
}

async function getPageData(videoId: string): Promise<{
  visitorData: string;
  clientVersion: string;
  availableLanguages: CaptionTrack[];
  metadata: VideoMetadata;
}> {
  let html: string;
  try {
    html = await httpsRequest({
      hostname: "www.youtube.com",
      path: `/watch?v=${videoId}`,
      method: "GET",
      headers: {
        "User-Agent": WEB_USER_AGENT,
        "Accept-Language": "en-US,en;q=0.9",
      },
    });
  } catch (err) {
    throw new Error(`Failed to fetch video page: ${(err as Error).message}`);
  }

  const visitorMatch = html.match(/"visitorData":"([^"]+)"/);
  const visitorData = visitorMatch?.[1] ?? "";

  const versionMatch = html.match(/"clientVersion":"([\d.]+)"/);
  const clientVersion = versionMatch?.[1] ?? DEFAULT_CLIENT_VERSION;

  const availableLanguages: CaptionTrack[] = [];
  const captionsMatch = html.match(/"captions":\{"playerCaptionsTracklistRenderer":\{"captionTracks":(\[[^\]]+\])/);
  if (captionsMatch) {
    try {
      const tracks = JSON.parse(captionsMatch[1]);
      for (const track of tracks) {
        if (track.languageCode) {
          availableLanguages.push({
            languageCode: track.languageCode,
            name: track.name?.simpleText ?? track.name?.runs?.[0]?.text ?? track.languageCode,
            isAutoGenerated: track.kind === "asr",
          });
        }
      }
    } catch {
      /* ignore parse errors */
    }
  }

  const titleMatch = html.match(/"videoDetails":\{.*?"title":"([^"]+)"/);
  const authorMatch = html.match(/"videoDetails":\{.*?"author":"([^"]+)"/);
  const subsMatch = html.match(/"subscriberCountText":\{"accessibility":\{"accessibilityData":\{"label":"([^"]+)"/);
  const viewsMatch = html.match(/"viewCount":"(\d+)"/);
  const dateMatch = html.match(/"publishDate":"([^"]+)"/);

  let subs = subsMatch?.[1] ?? "";
  subs = subs.replace(/ subscribers?/i, "").replace(/ thousand/i, "k").replace(/ million/i, "M").replace(/ billion/i, "B");

  const views = viewsMatch?.[1] ?? "";
  const viewNum = parseInt(views, 10);
  const viewsFormatted = Number.isNaN(viewNum)
    ? ""
    : viewNum >= 1_000_000
      ? (viewNum / 1_000_000).toFixed(1) + "M"
      : viewNum >= 1_000
        ? (viewNum / 1_000).toFixed(1) + "k"
        : views;

  const dateRaw = dateMatch?.[1] ?? "";
  const dateShort = dateRaw.split("T")[0];

  const metadata: VideoMetadata = {
    title: titleMatch?.[1] ?? "Unknown",
    author: authorMatch?.[1] ?? "",
    subscriberCount: subs,
    viewCount: viewsFormatted,
    publishDate: dateShort,
  };

  return { visitorData, clientVersion, availableLanguages, metadata };
}

/**
 * Fetches transcript using YouTube's internal get_transcript API.
 * Uses ANDROID client to bypass poToken enforcement.
 */
export async function getSubtitles(options: {
  videoID: string;
  lang?: string;
  enableFallback?: boolean;
}): Promise<SubtitleResult> {
  const { videoID, lang = "en", enableFallback = true } = options;

  if (!videoID || typeof videoID !== "string") {
    throw new Error("Invalid video ID: must be a non-empty string");
  }

  const { visitorData, availableLanguages, metadata } = await getPageData(videoID);

  let targetLang = lang;
  if (availableLanguages.length > 0) {
    const hasRequestedLang = availableLanguages.some((t) => t.languageCode === lang);
    if (!hasRequestedLang && enableFallback) {
      const hasEnglish = availableLanguages.some((t) => t.languageCode === "en");
      targetLang = hasEnglish ? "en" : availableLanguages[0]!.languageCode;
    } else if (!hasRequestedLang) {
      throw new Error(
        `Could not find ${lang} captions for ${videoID}. Available: ${availableLanguages.map((t) => t.languageCode).join(", ")}`
      );
    }
  }

  const params = buildParams(videoID, targetLang);
  const payload = JSON.stringify({
    context: {
      client: {
        hl: targetLang,
        gl: "US",
        clientName: "ANDROID",
        clientVersion: ANDROID_CLIENT_VERSION,
        androidSdkVersion: 30,
        visitorData,
      },
    },
    params,
  });

  let response: string;
  try {
    response = await httpsRequest(
      {
        hostname: "www.youtube.com",
        path: "/youtubei/v1/get_transcript?prettyPrint=false",
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": String(Buffer.byteLength(payload)),
          "User-Agent": ANDROID_USER_AGENT,
          Origin: "https://www.youtube.com",
        },
      },
      payload
    );
  } catch (err) {
    throw new Error(`Failed to fetch transcript API: ${(err as Error).message}`);
  }

  let json: unknown;
  try {
    json = JSON.parse(response) as Record<string, unknown>;
  } catch (err) {
    throw new Error(`Failed to parse YouTube API response. Preview: ${response.substring(0, 200)}`);
  }

  const j = json as { error?: { message?: string } };
  if (j.error) {
    throw new Error(`YouTube API error: ${j.error.message ?? "Unknown"}`);
  }

  const actions = (j as Record<string, unknown>).actions as Array<Record<string, unknown>> | undefined;
  const a0 = actions?.[0];

  const webSegs =
    (a0?.updateEngagementPanelAction as Record<string, unknown> | undefined)?.content as
      | Record<string, unknown>
      | undefined;
  const webSegments =
    (webSegs?.transcriptRenderer as Record<string, unknown> | undefined)?.content as
      | Record<string, unknown>
      | undefined;
  const webBody = (webSegments?.transcriptSearchPanelRenderer as Record<string, unknown> | undefined)
    ?.body as Record<string, unknown> | undefined;
  const webList = (webBody?.transcriptSegmentListRenderer as { initialSegments?: unknown[] } | undefined)
    ?.initialSegments;

  const elemCmd = a0?.elementsCommand as Record<string, unknown> | undefined;
  const transformArgs = (elemCmd?.transformEntityCommand as Record<string, unknown> | undefined)
    ?.arguments as Record<string, unknown> | undefined;
  const overwrite = (transformArgs?.transformTranscriptSegmentListArguments as Record<string, unknown> | undefined)
    ?.overwrite as { initialSegments?: unknown[] } | undefined;
  const androidSegs = overwrite?.initialSegments;

  const segments = webList ?? androidSegs ?? [];

  if (segments.length === 0) {
    throw new Error("No transcript available for this video. The video may not have captions enabled.");
  }

  const lines = (segments as Array<{
    transcriptSegmentRenderer?: {
      snippet?: { runs?: Array<{ text?: string }>; elementsAttributedString?: { content?: string } };
      startMs?: string;
      endMs?: string;
    };
  }>)
    .filter((seg) => seg?.transcriptSegmentRenderer)
    .map((seg) => {
      const r = seg.transcriptSegmentRenderer!;
      const webText = r.snippet?.runs?.map((x) => x.text ?? "").join("");
      const androidText = r.snippet?.elementsAttributedString?.content;
      const text = webText ?? androidText ?? "";
      const startMs = parseInt(r.startMs ?? "0", 10);
      const endMs = parseInt(r.endMs ?? "0", 10);
      return {
        text,
        start: startMs / 1000,
        dur: (endMs - startMs) / 1000,
      };
    })
    .filter((line) => line.text.length > 0);

  return {
    lines,
    requestedLang: lang,
    actualLang: targetLang,
    availableLanguages,
    metadata,
  };
}

/**
 * Fetch transcript and convert to TranscriptSegment[] format.
 */
export async function fetchTranscript(
  videoId: string,
  lang: string = "en"
): Promise<{ segments: TranscriptSegment[]; metadata: VideoMetadata } | null> {
  try {
    const result = await getSubtitles({ videoID: videoId, lang, enableFallback: true });
    const segments: TranscriptSegment[] = result.lines.map((line) => ({
      text: line.text,
      start: line.start,
      end: line.start + line.dur,
    }));
    return { segments, metadata: result.metadata };
  } catch {
    return null;
  }
}
